### ISSUE TITLE
How to specify different rank to each layer?

### ISSUE THREAD

**Issue by WilliamsToTo** [ruz048/AutoLoRA#1]
If I understand correctly, after the meta-training. We can get the optimal rank for each layer. And those optimal ranks can be different. 

- My first question is how to specify different ranks for each layer in the code. Because in your code in [lora_glue.py](https://github.com/ruz048/AutoLoRA/blob/main/finetune/lora_glue.py), all layers share the same rank.

  `lora_dim=8`
  `peft_config = LoraConfig(task_type="SEQ_CLS", inference_mode=False, r=lora_dim, lora_alpha=16, lora_dropout=0.1)`
  
  This is different from your paper.

- Another question is in section 4.4 of your paper. You mentioned the optimal rank is the number of $\alpha_{l}^{j}$ that higher than a threshold. Could you explain the reason behind it? Because as my understanding, the highest $\alpha_{l}^{j}$ should be the optimal rank.

**Comment by ruz048** [comment]
1. The rank is defined in globals.py file, and the code of peft library is changed (finetune/peft/tuners/lora.py) to initialize LoRA layers with rank defined in globals.py file. 
2. The $\alpha_l^j$ takes the value between 0 to 1, and it represents the importance of its corresponding rank-1 matrix $\Delta_l^j$. With a higher value of  $\alpha_l^j$, the rank-1 matrix should be kept instead of discarded. So the resulting optimal rank should be the number of rank-1 matrices kept, which is the number of $\alpha_l^j$ that is higher than a threshold.
